# Основы R, типы данных часть 1

http://re9ulus.github.io/2015/09/02/introduction_to_r_p1/

In [1]:
w <- 5
f <- 6

In [2]:
w

[1] 5

In [3]:
f

[1] 6

In [4]:
s <- w*f

In [5]:
s

[1] 30

In [7]:
p = s^3 / 4*w

In [8]:
p

[1] 33750

In [9]:
ls()    # Функция "ls" - отображает переменные в текущем окружении

[1] "f" "p" "s" "w"

In [10]:
rm(f)

In [11]:
ls()    # Функция "rm" - удаляет переменную из окружения

[1] "p" "s" "w"

Для полноценных программ исходный код сохраняется в R-скрипты, файлы с расширением **.R**.

Исполняется такой скрипт командой **Rscript square.R**.

In [ ]:
# Функция "cat" используется для вывода в консоль или файл

cat("Compute the square of pizza:\n")
pizza_radius <- 3
pizza_square <- pi * pizza_radius ^ 2
cat(pizza_square)

In [12]:
?sum

In [13]:
sum(1,3,5)

[1] 9

# Logical

Самым простым является логический тип данных logical. К нему относятся значения TRUE и FALSE, можно просто T и F. Еще logical соответствует значение NA, но сейчас это неважно.

Чтобы определить к какому типу относится переменная есть функция **class()**, которая принимает переменную и возвращает ее тип.

In [14]:
var <- FALSE

In [15]:
class(var)

[1] "logical"

In [16]:
class(TRUE)

[1] "logical"

In [18]:
TRUE && FALSE # и

[1] FALSE

In [19]:
TRUE || FALSE # или

[1] TRUE

In [20]:
!FALSE

[1] TRUE

# Numeric


Числовой тип данных представлен numeric и поддерживает основные арифметические операции.

In [21]:
1984

[1] 1984

In [22]:
2.5

[1] 2.5

In [23]:
class(2)

[1] "numeric"

In [24]:
class(4.5)

[1] "numeric"

In [26]:
6%%3

[1] 0

In [27]:
5%%3

[1] 2

Частным случаем numeric является целочисленный тип **integer**. Для указания что число является integer к нему дописывается **L**.

In [28]:
45L

[1] 45

In [29]:
class(45L)

[1] "integer"

Все integer являются numeric, но не все numeric являются integer.

# Character


Для хранения строк есть character, тут все просто.

In [31]:
'Hello world'

[1] "Hello world"

In [32]:
class("fine")

[1] "character"

In [33]:
"john" + "smith"

ERROR: Error in "john" + "smith": нечисловой аргумент для бинарного оператора


Конкатенация строк производится функцией "paste", "+" не работает для строк!

In [34]:
g <- paste("john", "smith")

In [35]:
g

[1] "john smith"

In [38]:
sprintf("Привіт") # Печатаем строку

[1] "Привіт"

In [41]:
name <- 'Maksym'

In [47]:
sprintf("Who is %s?", name)

[1] "Who is Maksym?"

In [50]:
f = substr("hello world", start = 2,stop = 5) # Получаем подстроку

In [51]:
f

[1] "ello"

In [52]:
# Заменяем подстроку
sub("table", "day", "It is your table")

[1] "It is your day"

# Complex

Тип данных для операций с комплексными числами:

In [53]:
z <- -1 +5i # Создание комплексного числа

In [54]:
z

[1] -1+5i

In [55]:
Re(z)  # Действительная часть

[1] -1

In [56]:
Im(z)  # Мнимая часть

[1] 5

In [57]:
Mod(z) # Модуль

[1] 5.09902

In [58]:
Arg(z)# Аргумент

[1] 1.768192

In [59]:
Conj(z) # Сопряженное комплексное число

[1] -1-5i

# Определяем и конвертируем типы

Чтобы проверить, принадлежит ли переменная к какому-либо типу можно использовать функции вида **is.***:

In [60]:
is.numeric(5)

[1] TRUE

In [61]:
is.integer(4.5)

[1] FALSE

In [63]:
is.character("g")

[1] TRUE

In [64]:
is.logical(TRUE)

[1] TRUE

 Для конвертации типов используются функции вида **as.***:

In [65]:
as.numeric(TRUE)

[1] 1

In [66]:
as.numeric("5")

[1] 5

In [67]:
as.integer(4.5)

[1] 4

In [68]:
as.numeric("geg")

Warning message in eval(expr, envir, enclos):
"в результате преобразования созданы NA"

[1] NA

# Векторы

Вектор в R это набор элементов одного типа. Создаются векторы функцией c(), сокращение от combine.

In [26]:
v = c(1,2,4,5)

In [27]:
v

[1] 1 2 4 5

In [28]:
class(v)

[1] "numeric"

In [29]:
is.vector(v)

[1] TRUE

In [30]:
is.vector(4)

[1] TRUE

In [31]:
stroki <- c("a","b","c") # Вектор строк

In [32]:
stroki

[1] "a" "b" "c"

In [33]:
class(stroki)

[1] "character"

In [34]:
is.vector(stroki)

[1] TRUE

In [35]:
length(v) # Длина вектора получается функцией `length()`

[1] 4

In [36]:
length(stroki)

[1] 3

In [37]:
sum(v)

[1] 12

In [38]:
sum(stroki)

ERROR: Error in sum(stroki): неправильный 'type' (character) аргумента


Каждому элементу вектора может быть присвоено имя. Сделать это можно несколькими способами:

In [39]:
names(v) <- stroki # С помощью функции names()

In [40]:
v

a    b    c <NA> 
   1    2    4    5

In [41]:
v <- c("g" = 4,"r"= 3,"t"= 6)

In [42]:
v

g r t 
4 3 6

In [43]:
v[1:2]

g r 
4 3

In [45]:
v[1]

g 
4

In [47]:
d  <- c(lite = 1,foor = 2, goot = 5)

In [48]:
d

lite foor goot 
   1    2    5

На самом деле, все базовые типы R являются векторами из 1 элемента.


In [49]:
day_number <- 1
day_title <- "Thursday"

In [50]:
is.vector(day_number)

[1] TRUE

In [52]:
is.vector(day_title)

[1] TRUE

In [56]:
length(day_number)

[1] 1

In [57]:
length(day_title) 

[1] 1

**При попытке создать вектор, содержащий элементы нескольких типов, все элементы будут приведены к наиболее общему типу.**

In [59]:
# Все numeric будут конвертированы в character
marks <- c(4,5,"A","B")

In [60]:
marks

[1] "4" "5" "A" "B"

In [61]:
class(marks)

[1] "character"

# Вычисления с векторами

**Операции над векторами выполняются поэлементно:**



In [62]:
e <- c(10,10,56)

In [64]:
e*3

[1]  30  30 168

In [67]:
sqrt(e)

[1] 3.162278 3.162278 7.483315

In [68]:
# Операции над несколькими векторами так же выполняются поэлементно
k <- c(4,5,78)

In [69]:
e - k

[1]   6   5 -22

In [70]:
e/k

[1] 2.5000000 2.0000000 0.7179487

In [73]:
e/c(1,2)

Warning message in e/c(1, 2):
"длина большего объекта не является произведением длины меньшего объекта"

[1] 10  5 56

In [74]:
e**k

[1]  1.000000e+04  1.000000e+05 2.283842e+136

In [75]:
# Каждый элемент вектора можно проверить на соответсиве условию и получить вектор logic значений


In [76]:
e <78

[1] TRUE TRUE TRUE

In [77]:
e/4567

[1] 0.002189621 0.002189621 0.012261879

In [78]:
e **3

[1]   1000   1000 175616

In [79]:
e < 56

[1]  TRUE  TRUE FALSE

# Элементы вектора, подмножества векторов


Обращение к элементам вектора происходит по индексу или имени, заключенному в квадратные скобки [].

O плохом: индексация в R начинается с 1.



In [80]:
remain <- c(veg = 15, lem = 6, apples = 6)

In [81]:
remain[1]

veg 
 15

In [83]:
remain['apples']

apples 
     6

Можно получить несколько элементов вектора, используя числовой вектор или вектор строк.

In [89]:
remain[c(1,2)]

veg lem 
 15   6

In [90]:
remain[1:3]

veg    lem apples 
    15      6      6

Если поставить перед индексом элемента знак минус -, этот элемент будет исключен из вектора. Удалять элементы по именам нельзя, только по индексам.

In [92]:
new_remain <- remain[-3]

In [93]:
remain

veg    lem apples 
    15      6      6

In [94]:
remain[-3]

veg lem 
 15   6

In [97]:
h <-remain[-c(1,2)] # Можно исключить сразу несколько элементов

In [98]:
h

apples 
     6

Подмножество элементов можно получить передав вектор logic значений. Будут выбраны элементы индексам которых соответствует значение TRUE.

In [99]:
# Выбираем первый и третий элементы
remain[c(TRUE,FALSE, TRUE)]

veg apples 
    15      6

In [103]:
# Если элементов в передаваемом векторе недостаточно, вектор будет зациклен до нужной длины
remain[c(FALSE,TRUE)]

lem 
  6

In [104]:
# Выбираем нечетные элементы
remain[remain %% 2!=0 ]

veg 
 15

# Матрицы
Матрица расширяет понятие вектора. Это тот же самый вектор, который может содержать элементы только одного типа, но теперь двумерный. Создается матрица функцией matrix(), с указанием количества строк или столбцов.

In [1]:
# Матрица содержащая элементы от 1 до 6 в две строки
matrix(1:6,nrow = 2)

[,1] [,2] [,3]
[1,] 1    3    5   
[2,] 2    4    6

In [2]:
matrix(1:6,ncol = 2)

[,1] [,2]
[1,] 1    4   
[2,] 2    5   
[3,] 3    6

In [7]:
# По умолчанию матрица заполняется по столбцам, для заполнения по строкам нужен параметр "byrow"
matrix(4:11, nrow = 2,byrow = TRUE)

[,1] [,2] [,3] [,4]
[1,] 4    5     6    7  
[2,] 8    9    10   11

In [8]:
# Если элементов недостаточно для заполнения всех строк и столбцов они будут циклически повторяться
matrix(1:3, nrow=3,ncol = 4, byrow = TRUE)

[,1] [,2] [,3] [,4]
[1,] 1    2    3    1   
[2,] 2    3    1    2   
[3,] 3    1    2    3

Второй способ создания матрицы состоит в комбинировании векторов по строкам или по столбцам, функциями rbind и cbind соответственно.

In [9]:
rbind(1:3, 7:9)

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 7    8    9

In [16]:
cbind(4:6,1:3)

[,1] [,2]
[1,] 4    1   
[2,] 5    2   
[3,] 6    3

Используя rbind и cbind можно добавить строку или столбец к уже существующей матрице.

In [17]:
m <- matrix(1:6, byrow = TRUE, nrow = 2)

In [18]:
m

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6

In [20]:
rbind(m, 7:9)

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6   
[3,] 7    8    9

In [24]:
cbind(m, 45:45)

[,1] [,2] [,3] [,4]
[1,] 1    2    3    45  
[2,] 4    5    6    45

Для присвоения имен строкам и столбцам матрицы есть функции **rownames** и **colnames**. Строки и столбцы могут быть проименованы и в момент создания матрицы параметром **dimnames**.

In [25]:
m <- matrix(1:9, nrow = 3, ncol = 3, byrow = TRUE)

In [26]:
m

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6   
[3,] 7    8    9

In [27]:
# Называем стоки
rownames(m) <- c("row1","row2", "row3")

In [28]:
# Называем столбцы
colnames(m) <- c("col1","col2", "col3")

In [29]:
m

col1 col2 col3
row1 1    2    3   
row2 4    5    6   
row3 7    8    9

In [31]:
# При создания матрицы
 m <- matrix(1:9, byrow = TRUE, nrow = 3, ncol = 3,
                dimnames = list(c("row1", "row2", "row3"),
                                c("col1", "col2", "col3")))

In [32]:
m

col1 col2 col3
row1 1    2    3   
row2 4    5    6   
row3 7    8    9

Как и векторы, матрицы хранят элементы только одного типа. При попытке сохранить в одной матрице элементы нескольких типов, или соединить матрицы разных типов используя **rbind** и **cbind** все элементы будут приведены к наиболее общему типу.

# Элементы матрицы, подмножества матриц
Для выбора элементов матрицы используются те же техники что и для векторов, с поправкой на двумерность матрицы.

In [36]:
m[1,3]

[1] 3

In [37]:
m[2,2]

[1] 5

In [42]:
m[1,]

col1 col2 col3 
   1    2    3

In [43]:
m[2,]

col1 col2 col3 
   4    5    6

In [44]:
m[3,]

col1 col2 col3 
   7    8    9

In [45]:
m[,1]

row1 row2 row3 
   1    4    7

In [46]:
m[,3]

row1 row2 row3 
   3    6    9

Можно выбирать сразу несколько элементов. Принципы те же, что и с векторами.

In [47]:
# Элементы на пересечении второй строки, первого и третьего столбца
m[2,c(1,3)] 

col1 col3 
   4    6

In [48]:
m[c(1,3),c(1,3)]

col1 col3
row1 1    3   
row3 7    9

In [50]:
# Элементы можно выбрать используя имена строк и столбцов.

m[c("row1","row2"), "col1"]

row1 row2 
   1    4

# Использование матриц

Матрицы поддерживают все стандартные арифметические операции. Выполняются операции над матрицами поэлементно, включая умножение и деление.

In [51]:
m

col1 col2 col3
row1 1    2    3   
row2 4    5    6   
row3 7    8    9

In [52]:
m +3

col1 col2 col3
row1  4    5    6  
row2  7    8    9  
row3 10   11   12

In [53]:
m -3

col1 col2 col3
row1 -2   -1   0   
row2  1    2   3   
row3  4    5   6

In [55]:
log(m)

col1     col2      col3    
row1 0.000000 0.6931472 1.098612
row2 1.386294 1.6094379 1.791759
row3 1.945910 2.0794415 2.197225

In [56]:
sin(m)

col1       col2       col3      
row1  0.8414710  0.9092974  0.1411200
row2 -0.7568025 -0.9589243 -0.2794155
row3  0.6569866  0.9893582  0.4121185

In [57]:
rowSums(m) # "rowSums" возвращает сумму элементов каждой строки

row1 row2 row3 
   6   15   24

In [58]:
colSums(m)# "colSums" возвращает сумму элементов каждого столбца

col1 col2 col3 
  12   15   18

In [59]:
# Транспонирование матриц осуществляется функцией "t()"
t(m)

row1 row2 row3
col1 1    4    7   
col2 2    5    8   
col3 3    6    9

In [61]:
# Для математической операции перемножения матриц необходимо использовать оператор %*%
 matrix(1:6, nrow = 3) %*% matrix(7:12, ncol = 3)

[,1] [,2] [,3]
[1,] 39   49    59 
[2,] 54   68    82 
[3,] 69   87   105